import type { Room } from '@/entities/room/model/types'
import type { Booking } from '@/entities/booking/model/types'

export const MOCK_ROOMS: Room[] = [
  {
    id: '1',
    name: 'Стандарт',
    description: 'Уютный номер с видом на город. Одна двуспальная кровать, кондиционер, Wi-Fi.',
    price: 3500,
    capacity: 2,
    amenities: ['Wi-Fi', 'Кондиционер', 'ТВ', 'Мини-бар'],
    imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600',
    available: true,
    category: 'standard',
  },
  {
    id: '2',
    name: 'Делюкс',
    description: 'Просторный номер с панорамным видом. Две кровати, джакузи, гардеробная.',
    price: 6500,
    capacity: 3,
    amenities: ['Wi-Fi', 'Кондиционер', 'ТВ', 'Джакузи', 'Балкон'],
    imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=600',
    available: true,
    category: 'deluxe',
  },
  {
    id: '3',
    name: 'Апартаменты',
    description: 'Полностью оборудованные апартаменты с кухней и гостиной. Идеально для длительного проживания.',
    price: 10500,
    capacity: 4,
    amenities: ['Wi-Fi', 'Кондиционер', 'Кухня', 'Гостиная', 'Стиральная машина'],
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600',
    available: false,
    category: 'apartment',
  },
  {
    id: '4',
    name: 'Эконом',
    description: 'Комфортный бюджетный номер. Две раздельные кровати.',
    price: 2200,
    capacity: 2,
    amenities: ['Wi-Fi', 'ТВ'],
    imageUrl: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600',
    available: true,
    category: 'economy',
  },
  {
    id: '5',
    name: 'Люкс',
    description: 'Роскошный номер с персональным консьержем. Угловой панорамный вид.',
    price: 18000,
    capacity: 2,
    amenities: ['Wi-Fi', 'Джакузи', 'Мини-бар', 'Балкон', 'Консьерж', 'Завтрак'],
    imageUrl: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=600',
    available: true,
    category: 'suite',
  },
  {
    id: '6',
    name: 'Семейный',
    description: 'Большой номер для семьи с детьми. Детская кроватка, игровая зона.',
    price: 7800,
    capacity: 5,
    amenities: ['Wi-Fi', 'Детская кроватка', 'Кондиционер', 'ТВ', 'Холодильник'],
    imageUrl: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=600',
    available: true,
    category: 'family',
  },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    roomId: '2',
    guestName: 'Анна Петрова',
    guestEmail: 'anna@example.com',
    checkIn: '2026-06-15',
    checkOut: '2026-06-18',
    guests: 2,
    totalPrice: 19500,
    status: 'confirmed',
    createdAt: '2026-06-01',
  },
]
